name: Deploy to GitHub

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Setup .yarnrc.yml
        run: |
          yarn config set npmScopes.fortawesome.npmRegistryServer $FA_REPO_URL
          yarn config set npmScopes.fortawesome.npmAlwaysAuth true
          yarn config set npmScopes.fortawesome.npmAuthToken $FA_TOKEN
        env:
          FA_REPO_URL: ${{ secrets.FA_REPO_URL }}
          FA_TOKEN: ${{ secrets.FA_TOKEN }}

      - name: Install dependencies
        run: yarn install

      - name: Build project
        run: yarn build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
