name: Deploy on production environment

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version: 18

      - name: Setup .yarnrc.yml
        run: |
          yarn config set npmScopes.fortawesome.npmRegistryServer $FA_REPO_URL
          yarn config set npmScopes.fortawesome.npmAlwaysAuth true
          yarn config set npmScopes.fortawesome.npmAuthIdent $FA_TOKEN
        env:
          FA_REPO_URL: ${{ secrets.FA_REPO_URL }}
          FA_TOKEN: ${{ secrets.FA_TOKEN }}

      - name: Install dependencies
        run: yarn install

      - name: Check Tag Duplicity
        run: yarn run dupcheck

      - name: Build project
        run: yarn generate

      - name: Publish app
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          projectName: danbooru-diffusion-prompt-builder
          directory: ./dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
